### ISSUE TITLE
Tries to install "how do I from source"

### ISSUE THREAD

**Issue by valdr** [btotharye/mycroft-skill-basichelp#1]
Mycroft installed on an Ubuntu 16.04 system from git clone 0.8.22, run with 'mycroft.sh start -d'

I was looking for a way to get a list of installable skills... or skills that are already installed from mycroft.
I typed "install help", and got this skill installed.
Not a problem. Let's see what it does...

```
>>  help is now installed and ready for use                                             
 help                                                                       
 help me                                                                 
 where are the docs
 how do I install from source
 >> installing
 >> Sorry, I could not find a skill matching how do i  from source
```
Ehm...

**Comment by btotharye** [comment]
the issue is the default skill-installer keyword is install, but if you say how do I install from source it should work, etc

**Comment by valdr** [comment]
@btotharye That's just it... As you can see I typed "how do I install from source", not using "Hey Mycroft" obviously, as I already have his attention. But instead of answering, Mycroft picks out "install", and tries to install the rest of the string... Which is odd, I'd say.

**Comment by valdr** [comment]
I thought Linux didn't require a reboot to install things properly... Mycroft does... It works now.
